
ALTER TABLE public.pets
  ADD COLUMN IF NOT EXISTS token TEXT,
  ADD COLUMN IF NOT EXISTS status_ativado BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS ultimo_acesso TIMESTAMP WITH TIME ZONE;

CREATE POLICY "Anyone can delete pets"
ON public.pets
FOR DELETE
USING (true);
